Todo.UI/Models/ViewModel/EditTodoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Todo.UI.Models.ViewModel
{
    public class EditTodoViewModel
    {
        [Required(ErrorMessage = "Task Name is required")]
        [MinLength(3, ErrorMessage = "Task Name should be atleast 3 character long.")]
        [MaxLength(30, ErrorMessage = "Task Name should not be more than 15 character long.")]
        public string NewTask { get; set; } = default!;

        [Required(ErrorMessage = "Assigned to is required")]
        public string SelectedAssignedTo { get; set; } = default!;


        [Required(ErrorMessage = "Description to is required")]
        public string Description { get; set; } = default!;
    }
}

Todo.UI/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Todo.UI.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Todo.UI/Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Todo.UI.Models.RequestModel;
using Todo.UI.Models.ResponseModel;
using Todo.UI.Models.ViewModel;

namespace Todo.UI.Pages
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public CreateTodoViewModel CreateTodoModel { get; set; } = new CreateTodoViewModel();

        private readonly string _baseUrl;
        private readonly IConfiguration _configuration;

        public List<SelectListItem> AssignedTo { get; set; } = new List<SelectListItem>();

        public CreateModel(IConfiguration configuration)
        {

            this._configuration = configuration;
            _baseUrl = _configuration.GetValue<string>("TodoApiUrl")!;
        }

        public IActionResult OnGet()
        {
            BindAssignedTo();
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Page();
                }

                CreateTodoRequestModel todoData = new()
                {
                    TaskName = CreateTodoModel.NewTask,
                    AssignedTo = CreateTodoModel.SelectedAssignedTo,
                    IsCompleted = false,
                    Description = CreateTodoModel.Description,
                    TaskType = "urgent"
                };
                using (HttpClient client = new HttpClient())
                {
                    HttpResponseMessage response = await client.PostAsJsonAsync<CreateTodoRequestModel>(_baseUrl + "/Todo/post", todoData);
                    response.EnsureSuccessStatusCode();

                    return RedirectToPage("Index");
                }
            }
            catch (Exception)
            {

                throw;
            }

        }

        public void BindAssignedTo()
        {
            try
            {
                using HttpClient client = new HttpClient();

                HttpResponseMessage response = client.GetAsync(_baseUrl + "/User").Result;
                response.EnsureSuccessStatusCode();
                string responseBody = response.Content.ReadAsStringAsync().Result;
                var responseModel = JsonConvert.DeserializeObject<List<UserResponseModel>>(responseBody)!;

                if (responseModel.Count > 0)
                {
                    var assigned = responseModel.Select(x => new SelectListItem
                    {
                        Text = x.EmailAddress,
                        Value = x.UserName
                    }).ToList();

                    AssignedTo = assigned;
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
    }



}

Todo.UI/Pages/EditTodo.cshtml.cs
using Newtonsoft.Json;
using Todo.UI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Todo.UI.Models.ResponseModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Todo.UI.Models.RequestModel;


namespace Todo.UI.Pages
{
    public class EditTodoModel : PageModel
    {
        [BindProperty] 
        public EditTodoViewModel EditTodoViewModel { get; set; } = new EditTodoViewModel();
        
        [FromQuery(Name = "todoId")]
        public int TodoId { get; set; }

        private readonly string _baseUrl;
        private readonly IConfiguration _configuration;
        public List<SelectListItem> AssignedTo { get; set; }


        public EditTodoModel(IConfiguration configuration)
        {
            _configuration = configuration;
            _baseUrl = _configuration.GetValue<string>("TodoApiUrl")!;
            AssignedTo = new List<SelectListItem>();
        }

        public async Task OnGetAsync(int todoId)
        {
            await PopulateAssignedToDropDown();
            await PopulateTodoDetails(todoId);
        }

        public async Task PopulateTodoDetails(int todoId)
        {
            using HttpClient client = new HttpClient();
            HttpResponseMessage response =
                await client.GetAsync(_baseUrl + "/Todo/fetchByProcedure?todoId=" + todoId);
            response.EnsureSuccessStatusCode();
            string responseBody = await response.Content.ReadAsStringAsync();
            var responseModel = JsonConvert.DeserializeObject<GetTodoResponseModel>(responseBody)!;

            EditTodoViewModel.NewTask = responseModel.taskName;
            EditTodoViewModel.Description = responseModel.description;
            EditTodoViewModel.SelectedAssignedTo =
                AssignedTo.FirstOrDefault(
                        x => x.Value == responseModel.assignedTo.ToString())!
                    .Value;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            CreateTodoRequestModel todoData = new()
            {
                Id = TodoId,
                TaskName = EditTodoViewModel.NewTask,
                AssignedTo = EditTodoViewModel.SelectedAssignedTo,
                IsCompleted = false,
                Description = EditTodoViewModel.Description,
                TaskType = "urgent"
            };
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.PostAsJsonAsync<CreateTodoRequestModel>(_baseUrl + "/Todo/post", todoData);
                response.EnsureSuccessStatusCode();

                return RedirectToPage("Index");
            }
        }
            
        
        public async Task PopulateAssignedToDropDown()
        {
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(_baseUrl + "/User");
                response.EnsureSuccessStatusCode();
                string responseBody = await response.Content.ReadAsStringAsync();
                var responseModel = JsonConvert.DeserializeObject<List<UserResponseModel>>(responseBody)!;

                if (responseModel.Count > 0)
                {
                    var assigned = responseModel.Select(x => new SelectListItem
                    {
                        Text = x.EmailAddress,
                        Value = x.UserName
                    }).ToList();

                    AssignedTo = assigned;
                }
            }
        }
    }
}

Todo.UI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Todo.UI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Todo.UI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using Todo.UI.Models.RequestModel;

namespace Todo.UI.Pages
{
    public class IndexModel : PageModel
    {

        private readonly ILogger<IndexModel> _logger;
        private readonly IConfiguration _configuration;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly string _baseUrl;
        public List<CreateTodoRequestModel> Todos { get; set; }



        public IndexModel(
            ILogger<IndexModel> logger,
            IConfiguration configuration,
            IHttpContextAccessor httpContextAccessor)
        {
            _logger = logger;
            _configuration = configuration;
            _httpContextAccessor = httpContextAccessor;
            _baseUrl = _configuration.GetValue<string>("TodoApiUrl")!;
        }

        public async Task OnGetAsync()
        {
            await ListTodos();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {

            using (HttpClient client = new HttpClient())
            {
                string deleteUrl = _baseUrl + $"/Todo?id={id}";

                HttpResponseMessage response = await client.DeleteAsync(deleteUrl);
                response.EnsureSuccessStatusCode();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostEdit(int id)
        {
            return RedirectToPage("/EditTodo", new { todoId = id });
        }

        public IActionResult OnPostCreateNew()
        {
            return RedirectToPage("/Create");
        }

        public async Task ListTodos()
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {

                    var token = _httpContextAccessor.HttpContext!.Session.GetString("Token");

                    if (!string.IsNullOrEmpty(token))
                    {
                        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                    }

                    HttpResponseMessage response = await client.GetAsync(_baseUrl + "/Todo");

                    var statusCode = response.StatusCode;

                    if(statusCode == System.Net.HttpStatusCode.Unauthorized)
                    {
                      
                       
                    }
                    else
                    {


                        response.EnsureSuccessStatusCode();
                        string responseBody = await response.Content.ReadAsStringAsync();
                        Todos = JsonConvert.DeserializeObject<List<CreateTodoRequestModel>>(responseBody)!;
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

Todo.UI/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json.Linq;

namespace Todo.UI.Pages
{
    public class LoginModel : PageModel
    {

        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public string ErrorMessage { get; private set; }

        private readonly string _baseUrl;
        private readonly IConfiguration _configuration;

        public LoginModel(
            IConfiguration configuration)
        {
            _configuration = configuration;
            _baseUrl = _configuration!.GetValue<string>("TodoApiUrl")!;
        }

        public void OnGet()
        {
        }


        public async Task<IActionResult> OnPost()
        {
            using (HttpClient client = new HttpClient())
            {
                string loginUrl = _baseUrl + $"/Authentication?userName={Username}&password={Password}";

                HttpResponseMessage response = await client.GetAsync(loginUrl);
                response.EnsureSuccessStatusCode();

                string tokenString = await response.Content.ReadAsStringAsync();

                HttpContext.Session.SetString("Token", tokenString);

                Response.Cookies.Append("AuthToken", tokenString, new CookieOptions { HttpOnly = true });

                return RedirectToPage("Index");
            }
        }
    }
}

Todo.UI/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Todo.UI.Pages
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            Response.Cookies.Delete("AuthToken");
            return RedirectToPage("/Login");
        }
    }
}

Todo.UI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Todo.UI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            try
            {
                int a = 10;
                int b = 0;


                _logger.LogInformation($"The first number entered by end user is {a}");
                _logger.LogInformation($"The second number entered by end user is {b}");



                if(b == 0)
                {
                    _logger.LogInformation("Divide by 0 is not allowed");
                    return;
                }

                int c = a / b;
            }
            catch (Exception ex)
            {
               _logger.LogError(ex.Message);
                throw;
            }
        }
    }

}

Todo.UI/Pages/About.cshtml
@page
@model Todo.UI.Pages.AboutModel
@{
}
<p>I am on About Screen</p>

Todo.UI/Pages/Create.cshtml
@page
@model Todo.UI.Pages.CreateModel
@{
}
<div class="text-center">
    <h1>Create New Todo</h1>
</div>
<form method="post">
    <div>
        <label asp-for="CreateTodoModel.NewTask"></label>
        <input type="text" asp-for="CreateTodoModel.NewTask" class="form-control" placeholder="Please enter a new item" />
        <span style="color:red" asp-validation-for="CreateTodoModel.NewTask"></span>
    </div>
    <div>
        <label asp-for="AssignedTo"></label>
        <select asp-for="CreateTodoModel.SelectedAssignedTo" class="form-control" asp-items="Model.AssignedTo">
            <option value="">Please Select</option>
        </select>
    </div>
    <div>
        <label asp-for="CreateTodoModel.Description"></label>
        <input type="text" asp-for="CreateTodoModel.Description" class="form-control" placeholder="Please enter description" />
        <span style="color:red" asp-validation-for="CreateTodoModel.Description"></span>
    </div>
    <br />

    <button class="btn btn-primary" type="submit">Add New</button>
</form>

Todo.UI/Pages/EditTodo.cshtml
@page
@model Todo.UI.Pages.EditTodoModel
@{
}
<div class="text-center">
    <h1>Edit Existing Todo</h1>
</div>
<form method="post">
    <div>
        <label asp-for="EditTodoViewModel.NewTask"></label>
        <input type="text" asp-for="EditTodoViewModel.NewTask" class="form-control" placeholder="Please enter a new item" />
        <span style="color:red" asp-validation-for="EditTodoViewModel.NewTask"></span>
    </div>
    <div>
        <label asp-for="AssignedTo"></label>
        <select asp-for="EditTodoViewModel.SelectedAssignedTo" class="form-control" asp-items="Model.AssignedTo">
            <option value="">Please Select</option>
        </select>
    </div>
    <div>
        <label asp-for="EditTodoViewModel.Description"></label>
        <input type="text" asp-for="EditTodoViewModel.Description" class="form-control" placeholder="Please enter description" />
        <span style="color:red" asp-validation-for="EditTodoViewModel.Description"></span>
    </div>
    <br />

    <button class="btn btn-success" type="submit">Update</button>


</form>

Todo.UI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<br />
<div class="container">
    <div class="text-center">
        <h1>Todo's List</h1>
    </div>
    <div class="text-right">
        <form method="post">
            <button type="submit" asp-page-handler="CreateNew" class="btn btn-primary">Add New</button>
        </form>
    </div>
    <br />
    @if (Model.Todos == null || !Model.Todos.Any())
    {
        <div class="alert alert-warning" role="alert">
            No Pending Todos
        </div>
    }
    else
    {
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Task Name</th>
                    <th>Description</th>
                    <th>Assigned To</th>
                    <th>Completed</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var todos in Model.Todos)
                {
                    <tr>
                        <td>
                            @todos.Id
                        </td>
                        <td>
                            @todos.TaskName
                        </td>
                        <td>
                            @todos.Description
                        </td>
                        <td>
                            @todos.AssignedTo
                        </td>
                        <td>
                            @todos.IsCompleted
                        </td>
                        <td>
                            <form method="post" asp-page-handler="Edit" asp-route-id="@todos.Id">
                                <button class="btn btn-primary" type="submit">Edit</button>
                            </form>
                        </td>
                        <td>
                            <form method="post" asp-page-handler="Delete" asp-route-id="@todos.Id">
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

Todo.UI/Pages/Login.cshtml
@page
@model Todo.UI.Pages.LoginModel
@{
}
<h2>Login</h2>

<form method="post">
    <div class="container-fluid">
        <div>
            <label for="username">Username</label>
            <input class="form-control" type="text" id="username" name="Username" />
        </div>
        <div>
            <label for="password">Password</label>
            <input class="form-control" type="password" id="password" name="Password" />
        </div>
        <br />
        <button type="submit">Login</button>
    </div>
</form>

@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <p style="color:red;">@Model.ErrorMessage</p>
}

Todo.UI/Pages/Logout.cshtml
@page
@model Todo.UI.Pages.LogoutModel
@{
}